services:
  - type: web
    name: app
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt --verbose
    startCommand: gunicorn --bind=0.0.0.0:$PORT app:app